name: Update-README-blank

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
      - uses: Readme-Workflows/recent-activity@v2.4.1
      - uses: andresparrav/andresparrav@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
